bookings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name='index'),
    path('guest_detail/<int:id>',views.guest_detail,name='guest_detail'),
    path('handlerequest/',views.handlerequest,name='handlerequest')
]

home/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('our_rooms/',views.our_rooms,name='our_rooms'),

]

hotel/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views as home_views
from room import views as room_views
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('home/', include('home.urls')),
    path('room/',include('room.urls')),
    path('bookings/',include('bookings.urls')),
    path('user/',include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('about/',home_views.about,name='about'),
    path('contact/',home_views.contact,name='contact'),
    path('room/<int:id>/<slug:slug>',home_views.room_details,name='room_details'),
    path('search/',home_views.search,name='search'),

    path('login/',user_views.login_form,name='login_form'),
    path('logout/',user_views.logout_func,name='logout_func'),
    path('signup/',user_views.signup_form,name='signup_form'),


]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookings/models.py
# Create your models here.
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from room.models import Room
from django.contrib.auth.models import User


# Create your models here.
class Guest(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    room=models.ForeignKey(Room,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    phone=models.IntegerField()
    address = models.CharField(blank=True, max_length=150)
    country = models.CharField(blank=True, max_length=20)
    check_in=models.DateTimeField()
    check_out=models.DateTimeField()
    stay=models.IntegerField(default=0)

    def __str__(self):
        return self.room.name

    @property
    def totalamount(self):
        return self.stay * self.room.price

bookings/forms.py
from django.forms import ModelForm

from bookings.models import Guest


class GuestForm(ModelForm):
    class Meta:
        model = Guest
        fields =['first_name','last_name','email','phone','address','country','check_in','check_out']

bookings/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse, redirect, render
from django.views.decorators.csrf import csrf_exempt
from Paytm import Checksum
from bookings.forms import GuestForm
from bookings.models import Guest
from user.models import UserProfile

MERCHANT_KEY='UkuUb!W%XMMZsDMo'
# Create your views here.
def index(request):
    return HttpResponse("hy")

@login_required(login_url='/login')
def guest_detail(request,id):
    current_user = request.user
    # profile = UserProfile.objects.get(user_id=current_user.id)
    if request.method == 'POST':  # if there is a post
        form = GuestForm(request.POST)
        if form.is_valid():
            data = Guest()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.email = form.cleaned_data['email']
            data.phone = form.cleaned_data['phone']
            data.address = form.cleaned_data['address']
            data.country=form.cleaned_data['country']
            data.check_in= form.cleaned_data['check_in']
            data.check_out= form.cleaned_data['check_out']

            # guest=Guest.objects.filter(user_id=current_user.id,room_id=id)
            guest=Guest.objects.filter(room_id=id)
            print(guest)
            if guest:
                for rs in guest:
                    print(rs.check_in)
                    print(rs.check_out)
                    print(data.check_in)
                    print(data.check_out)
                    if data.check_in<=rs.check_in and data.check_out>=rs.check_out:
                        print("error1")
                        messages.warning(request,"Room already booked on these days")
                        break
                        
                    elif data.check_in<=rs.check_in and data.check_out>=rs.check_in:
                        print("error2")

                        messages.warning(request,"Room already booked on these days")
                        break

                    elif data.check_in==rs.check_in and data.check_out==rs.check_out:
                        messages.warning(request,"Room already booked on these days")
                        break
                        
                    elif data.check_in>=rs.check_in and data.check_out>=rs.check_out and data.check_in>data.check_out:
                        print("error3")
                        messages.warning(request,"Room already booked on these days")
                        break
                        
                    elif data.check_in>rs.check_in and data.check_out<=rs.check_out:
                        print("error4")
                        messages.warning(request,"Room already booked on these days")
                        break

                    else: 
                        result=data.check_out-data.check_in
                        data.stay=result.days
                        data.user_id = current_user.id
                        data.room_id=id
                        if data.check_out<=data.check_in:
                            messages.warning(request,"Check out date should be greater than Check In")
                            break
                        else:
                            data.save()
                            oid=data.id
                            param_dict = {
                            'MID':'NdpDYp66468182668374',
                            'ORDER_ID':str(data.id),
                            'TXN_AMOUNT':str(data.totalamount),
                            'CUST_ID':current_user.email,
                            'INDUSTRY_TYPE_ID':'Retail',
                            'WEBSITE':'worldpressplg',
                            'CHANNEL_ID':'WEB',
                            'CALLBACK_URL':'http://localhost:8000/bookings/handlerequest/',
                            }
                            param_dict['CHECKSUMHASH']=Checksum.generate_checksum(param_dict,MERCHANT_KEY)
                            return render(request,'paytm.html',{'param_dict':param_dict})
                            messages.success(request, "Room has been booked. Thank you ")
            else:
                result=data.check_out-data.check_in
                data.stay=result.days
                data.user_id = current_user.id
                data.room_id=id
                if data.check_out<=data.check_in:
                    messages.warning(request,"Check out date should be greater than Check In")
                else:
                    data.save()
                    oid=data.id
                    param_dict = {
                    'MID':'NdpDYp66468182668374',
                    'ORDER_ID':str(oid),
                    'TXN_AMOUNT':str(data.totalamount),
                    'CUST_ID':current_user.email,
                    'INDUSTRY_TYPE_ID':'Retail',
                    'WEBSITE':'worldpressplg',
                    'CHANNEL_ID':'WEB',
                    'CALLBACK_URL':'http://localhost:8000/bookings/handlerequest/',
                    }
                    param_dict['CHECKSUMHASH']=Checksum.generate_checksum(param_dict,MERCHANT_KEY)
                    return render(request,'paytm.html',{'param_dict':param_dict})
                    messages.success(request, "Room has been booked. Thank you ")

        else:
            # return redirect("/")
            messages.warning(request, form.errors)

    form=GuestForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context={'form':form,'profile':profile}
    return render(request, 'guest_form.html',context)
 

@csrf_exempt
def handlerequest(request):
    form=request.POST
    response_dict={}
    for i in form.keys():
        response_dict[i]=form[i]
        if i == 'CHECKSUMHASH':
            checksum=form[i]
    verify=Checksum.verify_checksum(response_dict,MERCHANT_KEY,checksum)
    if verify:
        if response_dict['RESPCODE']=='01':
            print('booking successfull')
        else:
            print('booking failed because' + response_dict['RESPMSG'])
    return render(request,'order_completed.html',{'response':response_dict})

bookings/templates/guest_form.html
{%extends 'base.html'%}
{%block title %}Order Page{% endblock%}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keyword }}{% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Page</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			 <div class="row">

                  <Form action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Guest Details</h4>
                            </div>
                            <p><label for="id_first_name">First name:</label>
                                <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
                            <p><label for="id_last_name">Last name:</label>
                                <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                            <p><label for="id_last_name">Email:</label>
                                <input type="email" name="email"  value="{{ profile.user.email }}" class="input" required id="id_last_name"></p>
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="10" id="id_phone"></p>
                            <p><label for="id_city">Check In:</label>
                                <input type="date" name="check_in"  class="input" maxlength="20" id="id_phone"></p>  
                                 <p><label for="id_city">Check Out:</label>
                                <input type="date" name="check_out"  class="input" maxlength="20" id="id_phone"></p>  
                            <p><label for="id_first_name">Country :</label>
                                <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
                            <div class="pull-right">
                                <button  type="submit" class="primary-btn">Book Now</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">

                    </div>
                    <div class="col-md-6">
                      
                    </div>
            </Form>

							
						 
                        </div>
						<!-- /row -->
				
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
{% endblock %}

bookings/templates/order_completed.html
{%extends 'base.html'%}
{%block title %}Order Completed{% endblock%}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keyword }}{% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Booking Completed</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			        <div class="row">
				 <div class="col-md-12">
						<div class="order-summary clearfix">
							<div class="section-title">
								<h3 class="title">Booking Completed</h3>
							</div>
							   <hr>
                        {% comment %} <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2> {% endcomment %}
                        <hr>
                        <h3>Your room has been booked</h3>
                        {% comment %} <h3>Order Code : {{ ordercode }}</h3> {% endcomment %}
                        <h3>Thank You</h3>
                        <hr>
						</div>

					</div> 
							
						 
                        </div>
						<!-- /row -->
				
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
{% endblock %}

bookings/templates/paymentstatus.html
{%extends 'base.html'%}
{%block title %}Payment Status{% endblock%}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keyword }}{% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}
<h2>Payment status regarding {{response.ORDERID}}</h2>
{% if response.RESPCODE == '01' %}
<h1>BOOKING SUCCESSFUL</h1>
{% else %}
<h1>BOOKING FAILED</h1>
{% endif %}
{%endblock%}

bookings/templates/paytm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paytm merchant payment page</title>
</head>
<body>
<h1>Redirecting you to the merchant....</h1>
<h1>Please do not refresh your page....</h1>
<form action="https://securegw-stage.paytm.in/order/process" method="post" name="paytm">
    {% for key, value in param_dict.items %}
    <input type="hidden" name="{{key}}" value="{{value}}">
    {% endfor %}

</form>
</body>
<script>
document.paytm.submit()
</script>
</html>